create database customer_behavior;
drop table customer;
select * from customer;
use customer__behavior;

-- Q1. What is the total revenue generated by male vs.female customers?
select gender,sum(purchase_amount)as revenue 
from customer 
group by gender;

﻿-- Q2. Which customers used a discount but still spent more than the average purchase amount?
 
 select * from customer;
 
 SELECT 
    *
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            ROUND(AVG(purchase_amount), 2)
        FROM
            customer AS a);
 
 -- ﻿Q3.Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased, ROUND(avg(review_rating), 2) AS rating
FROM
    customer
GROUP BY item_purchased
ORDER BY rating DESC
LIMIT 5;

 -- ﻿Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
 
 SELECT 
    shipping_type, ROUND(AVG(purchase_amount)), 2
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.?

select * from customer;

select subscription_status,
count(customer_id) as total_customer,
round(avg(Purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from 
	customer
    group by subscription_status;

-- Q6.Which 5 products have the highest percentage of purchases with discounts applied?

select * from customer;

SELECT 
    Item_Purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE
        WHEN Discount_Applied = 'Yes' THEN 1
        ELSE 0
    END) AS discounted_purchases,
    ROUND(SUM(CASE
                WHEN Discount_Applied = 'Yes' THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*),
            2) AS discount_percentage
FROM
    customer
GROUP BY Item_Purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. ??

WITH customer_type AS (
SELECT customer_id,previous_purchases,
 CASE 
  WHEN previous_purchases = 1 THEN 'New Customer' 
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Cutomer'  
        ELSE 'Loyal Customer' 
 END AS customer_segment FROM customer) 

SELECT customer_segment,count(*) AS count_of_customer
FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

select * from customer;

WITH item_counts AS ( 
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts 
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

-- First Method

SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,

    COUNT(*) AS total_customers,

    SUM(CASE 
            WHEN subscription_status = 'Yes' THEN 1 
            ELSE 0 
        END) AS subscribed_customers,

    ROUND(
        SUM(CASE 
                WHEN subscription_status = 'Yes' THEN 1 
                ELSE 0 
            END) * 100.0 / COUNT(*), 2
    ) AS subscription_percentage

FROM customer

GROUP BY customer_type;



-- second Method 

SELECT 
 subscription_status,
 COUNT(customer_id) as repeat_buyers 
FROM customer
WHERE previous_purchases > 5 
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT * FROM customer;


SELECT 
 age_group as Age_Group,
 COUNT(age_group) Age_count,
 SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY age_group
ORDER BY Revenue DESC;